### ISSUE TITLE
Not displaying table preview for a Postgres database

### ISSUE THREAD

**Issue by alexandresobolevski** [plotly/plotly-database-connector#129]
The user has data on a localhost Postgres database of the following format:
> I have defined encoding as UTF8. 

Example of tables: 

 [Fleet_data] ------- imported from IMO_numbers.csv [37 rows]
num,group,company,company2,name,type,flag,IMO
1,ANABAC,Pevasa,Pevasa,Playa de Bakio,Atunero,Spain,9010345
2,ANABAC,Pevasa,Pevasa,Playa de Ris,Atunero,Spain,9684548
3,ANABAC,Pevasa,Pevasa,Playa de Azkorri,Atunero,Cabo Verde,9476111
4,ANABAC,Pevasa,Pevasa,Playa de Noja,Atunero,Spain,8806955

 [AObuoy_data] ------- imported from ATLFAD.csv [1,660,000 rows]
"row.names","vessel","buoy_type","code","date","day","time","lat","lon","vel"
268,7385461,"M","M3I207461","2016-06-29",29,7.4,56.42,101.42,0
722,7385461,"M","M3I220566","2016-06-23",23,21.33,56.42,101.42,0
723,7385461,"M","M3I220566","2016-06-24",24,21.33,56.42,101.42,0
728,7385461,"M","M3I220566","2016-06-29",29,21.32,56.42,101.42,0

When querying the table preview an error occurs.
![screen shot 2017-01-25 at 9 27 45 am](https://cloud.githubusercontent.com/assets/13302110/22294295/bc44d4ba-e2e0-11e6-87ed-7b386902deaa.png)

**Comment by chriddyp** [comment]
closed until we can reproduce
