### ISSUE TITLE
Need to allow for custom origins for On-Premise requests to the local connector

### ISSUE THREAD

**Issue by BRONSOLO** [plotly/plotly-database-connector#145]
Currently only select Plotly domains are allows: 

https://github.com/plotly/plotly-database-connector/blob/abf60d3cf0da4b520737f85002751a0d538c3342/backend/settings.js#L26-L30

This issue is currently being hit by matthews@porch

cc @chriddyp @scjody

**Comment by BRONSOLO** [comment]
![image](https://cloud.githubusercontent.com/assets/1909107/25672368/3696cd32-3001-11e7-938e-4ec5d11bde92.png)

**Comment by BRONSOLO** [comment]
Apparently this can be configured via the Replicated YAML -- currently investigating!

**Comment by BRONSOLO** [comment]
Modifying `~/.plotly/connector/settings.yaml` to include the line below solves the issue. 

```
CORS_ALLOWED_ORIGINS: ['https://buildly.plot.ly']
```

**Comment by chriddyp** [comment]
closed in the latest release
