### ISSUE TITLE
Notes from a fresh install

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly-database-connector#151]
I just did a fresh install on my mac, keeping notes about ways to make the experience better. Just to keep track of them, here they are in order that I encountered them:

- [ ] I didn’t see a “copy to applications” link in the dmg, even though it's shown in the tutorial.
- [x] pages for individual databases from tutorial https://help.plot.ly/database-connectors/personal-login/ are broken (ie https://help.plot.ly/plotly-databases/mssql ) 
- [x] It says “setup connections” but that's inside a tab that only supports one connection.
- [ ] include example databases *in the app itself* - that would also help with the fact that the instructions are unclear on a few points: what’s the database name (for mysql I had to get that from the grayed out “connected” image), do you need SSL, is the port required… also it’s hard to even find the example databases, though that may be just because of the previous item.
- [x] setting up a connection in /create/, why do you have to tell it if your connection is http or https? Isn’t that part of the URL you’re pasting anyway?
- [x] I understand it was a lot of work fur *us* to get automatic SSL set up… but now it should be hidden. When I see “Plotly has generated a unique SSL certificate for you” it sounds like I need to do something with that.
- [x] “Check if your database is built with SSL support. Note that this is different than the SSL connection that Plotly initializes for you automatically” is confusing - can we change to something like (if I'm understanding it correctly) “Does your database require that you connect to it via SSL? Note that this is just the connection between this app and your database; connections to plot.ly or your plotly instance are always encrypted.” Do we even need to ask this question? Can't we try to connect over SSL, and then try without if it fails (perhaps with some indication like a locked or unlocked icon, and corresponding tooltip, to show what we did)?
- [x] Preview Database doesn’t seem like a “step” per se - make it a modal? And the rest seems like it should be collapsed into kind of a status bar just showing what step you're on right now, because the app knows what needs to come next... so then the whole UI would fit on screen without scrolling (though it seems fine to leave FAQ below on scroll)
- [x] It’s “An SSL” and “An SQL” not “A SSL”
- [x] I’m assuming a scheduled query will not communicate via the web browser, but will talk directly to the plotly server (so you can close the workspace where you set this up)? Will it update what you see in the workspace too, if you still have that query open? What if you open it again?
- [x] The url you get - `https://alex-#####.plotly-connector.com:####` - looks like a public server, which could freak people out re: security. I see the description of this in the FAQ but I wouldn't have known to look there since it's under the heading "How do you generate certificates for a localhost web server?" and anyway this seems important enough to warrant a tooltip link or something right next to the url itself.
- [x] the "Click to open Query Editor" link does bring in the url for you (it wasn't clear that it would, since after that there are instructions for what to do with the url), but oddly still makes you go through the import modal before you see it. Both options should be available (new workspace window with the connection open, and bringing this url into an already open workspace window) but they need to be presented such that it doesn't look like they are two steps in the same process.
- [x] Preview Database would be really useful inside the workspace - at least a list of column names (and data types?) that you can expand inside the "available tables" list, but some representative values are also really useful when constructing queries, as sometimes it's not obvious what format values have in a column.
- [x] The app icon is super generic, and the top links (Plans and Pricing / Chart Creator and SQL Editor / Documentation / Request a Connector) are unstyled.

**Comment by jackparmer** [comment]
These are pretty much all take care of now. You'll have to create a new list for next week's release @alexcjohnson :)
