### ISSUE TITLE
sqlite3 node-gyp build does not work when packaged for windows and linux

### ISSUE THREAD

**Issue by alexandresobolevski** [plotly/plotly-database-connector#40]

**Comment by yech1990** [comment]
still not work after 96608bc

**Comment by chriddyp** [comment]
creating linux and windows builds natively on CircleCI and AppVeyor now

**Comment by spuschel** [comment]
Hi, I'm trying to connect to Sqlite on mac osx with no luck. The message I'm getting in the Connector interface, tab "2. Preview" is 

> Hm.. there was an error loading up your tables
{"status":500,"content":{"error":{"message":"Please install sqlite3 package manually"}}}

Of course, sqlite3 is installed. Anyway, I get an SSL Certificate but when I access the online Graph maker it displays the message:

> Hm... an error occurred fetching SQL Tables.

Any clues?

**Comment by n-riesco** [comment]
@spuschel @webdog Are you still unable to use sqlite with our latest release? If so, please, open a new issue.
