### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly-database-connector#51]
Plotly 2.0 runs over HTTPS but the connector server is running on HTTP. To connect Plotly 2.0 to the SQL connector the user needs to update their web browser settings to allow for insecure HTTP connections. 

Here is the setting in Chrome:
![image](https://cloud.githubusercontent.com/assets/1280389/16996601/0199c868-4e80-11e6-925e-6329e89d8d6f.png)

Once this is enabled, Plotly 2.0 can connect to the connector but the connection is un-encrypted over HTTP. If you are running this locally, then this connection is just between your web browser and localhost, data isn't traveling over any other network.

To make these connections secure over a network (e.g. running the connector as a server) this app should use an SSL certificate and run over HTTPS.

**Comment by alexandresobolevski** [comment]
If you are using the Plotly Database Connector v0.0.4 or later and you are using a MacOSX or Linux operating systems, follow these steps to setup your https connection from your computer to plot.ly when transferring data.

![step0](https://cloud.githubusercontent.com/assets/13302110/17672189/21309544-62e9-11e6-874e-360fd95b09b8.png)
![step1](https://cloud.githubusercontent.com/assets/13302110/17672191/23c1a078-62e9-11e6-8528-35d719ec6c55.png)
![step2](https://cloud.githubusercontent.com/assets/13302110/17672197/2a6abd24-62e9-11e6-9b37-25a3298c0b84.png)
![step3](https://cloud.githubusercontent.com/assets/13302110/17672200/312eda50-62e9-11e6-8cae-0a126592c48e.png)
![step4](https://cloud.githubusercontent.com/assets/13302110/17672209/3d87807c-62e9-11e6-82e2-b14db34edf05.png)
![step5](https://cloud.githubusercontent.com/assets/13302110/17672216/426df1b6-62e9-11e6-9db2-c3ae2244b7ed.png)
![step6](https://cloud.githubusercontent.com/assets/13302110/17672219/45f0cbe2-62e9-11e6-9fea-da5a98d2ed7f.png)
![step7](https://cloud.githubusercontent.com/assets/13302110/17672223/49d7690a-62e9-11e6-9a9e-c726260d5f1a.png)
![step8](https://cloud.githubusercontent.com/assets/13302110/17672227/4cd3ed2c-62e9-11e6-8cc4-74e6d76c088d.png)

**Comment by alexandresobolevski** [comment]
discussed and progress updated [here](https://github.com/plotly/streambed/issues/8846)

**Comment by chriddyp** [comment]
Closed and available as part of version 2.0 https://github.com/plotly/plotly-database-connector/releases
