### ISSUE TITLE
Redshift support

### ISSUE THREAD

**Issue by dudleycarr** [plotly/plotly-database-connector#75]
The Postgresql driver returns the following error when trying to connect to a Redshift server. Some Postgresql clients are able to work with Redshift. If that's not workable, any plans to add support for Redshift?

```
$11:22:53 GMT-0700 (PDT) - $[object Object]
$11:22:53 GMT-0700 (PDT) - $[object Object]
$11:22:53 GMT-0700 (PDT) - $Querying: SELECT datname AS database FROM pg_database WHERE datistemplate = false;
$11:22:53 GMT-0700 (PDT) - $Creating a connection for user dudleycarr
```

**Comment by alexandresobolevski** [comment]
Support for Redshift is certainly in the pipeline. Let me see over the weekend if it can be quickly implemented by using a similar flow to the current Postgresql connection.

**Comment by alexandresobolevski** [comment]
Hey @dudleycarr , there is a PR #77 for Redshift support, as soon as that is merged into master you could could clone the repo and see if that works for you.
