### ISSUE TITLE
API: OAuth2 support

### ISSUE THREAD

**Issue by alexandresobolevski** [plotly/plotly-database-connector#99]
@scjody could I get a more specific idea of a response you expect to get from the connector's `${connectorURL}:9494/oath2` endpoint

**Comment by scjody** [comment]
No response is needed from that endpoint.  You just need to store the token so that you can use it on future requests.

As a reminder, here's some really good information on OAuth 2.  We're using the implicit flow.

**Comment by scjody** [comment]
https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2
